const TOKEN = 'YOUR_BOT_TOKEN';
const LOGO  = 'https://a.top4top.io/p_3642arlta1.png';
const PAGE_SIZE = 20;

const RECITERS = [
    { name: 'مشاري راشد العفاسي',    server: 'https://server8.mp3quran.net/afs',   ayahFolder: 'Alafasy_128kbps'           },
    { name: 'محمود خليل الحصري',     server: 'https://server13.mp3quran.net/husr',  ayahFolder: 'Husary_128kbps'            },
    { name: 'محمد صديق المنشاوي',    server: 'https://server10.mp3quran.net/minsh', ayahFolder: 'Minshawy_Murattal_128kbps' },
    { name: 'ماهر المعيقلي',         server: 'https://server12.mp3quran.net/maher', ayahFolder: 'MaherAlMuaiqly128kbps'     },
    { name: 'سعد الغامدي',           server: 'https://server6.mp3quran.net/s_gmd',  ayahFolder: 'Ghamdi_40kbps'            },
    { name: 'محمد جبريل',            server: 'https://server8.mp3quran.net/jbrl',   ayahFolder: 'Muhammad_Jibreel_128kbps'  },
];

const SURAH_AYAH_COUNTS = [
     7, 286, 200, 176, 120, 165, 206,  75, 129, 109,
   123, 111,  43,  52,  99, 128, 111, 110,  98, 135,
   112,  78, 118,  64,  77, 227,  93,  88,  69,  60,
    34,  30,  73,  54,  45,  83, 182,  88,  75,  85,
    54,  53,  89,  59,  37,  35,  38,  29,  18,  45,
    60,  49,  62,  55,  78,  96,  29,  22,  24,  13,
    14,  11,  11,  18,  12,  12,  30,  52,  52,  44,
    28,  28,  20,  56,  40,  31,  50,  40,  46,  42,
    29,  19,  36,  25,  22,  17,  19,  26,  30,  20,
    15,  21,  11,   8,   8,  19,   5,   8,   8,  11,
    11,   8,   3,   9,   5,   4,   7,   3,   6,   3,
     5,   4,   5,   6
];

const SURAHS = [
    { number: 1,   name: 'الفاتحة',    nameEn: 'Al-Fatiha'      },
    { number: 2,   name: 'البقرة',     nameEn: 'Al-Baqara'      },
    { number: 3,   name: 'آل عمران',   nameEn: 'Aal-Imran'      },
    { number: 4,   name: 'النساء',     nameEn: 'An-Nisa'        },
    { number: 5,   name: 'المائدة',    nameEn: 'Al-Maida'       },
    { number: 6,   name: 'الأنعام',    nameEn: 'Al-Anam'        },
    { number: 7,   name: 'الأعراف',    nameEn: 'Al-Araf'        },
    { number: 8,   name: 'الأنفال',    nameEn: 'Al-Anfal'       },
    { number: 9,   name: 'التوبة',     nameEn: 'At-Tawba'       },
    { number: 10,  name: 'يونس',       nameEn: 'Yunus'          },
    { number: 11,  name: 'هود',        nameEn: 'Hud'            },
    { number: 12,  name: 'يوسف',       nameEn: 'Yusuf'          },
    { number: 13,  name: 'الرعد',      nameEn: 'Ar-Rad'         },
    { number: 14,  name: 'إبراهيم',    nameEn: 'Ibrahim'        },
    { number: 15,  name: 'الحجر',      nameEn: 'Al-Hijr'        },
    { number: 16,  name: 'النحل',      nameEn: 'An-Nahl'        },
    { number: 17,  name: 'الإسراء',    nameEn: 'Al-Isra'        },
    { number: 18,  name: 'الكهف',      nameEn: 'Al-Kahf'        },
    { number: 19,  name: 'مريم',       nameEn: 'Maryam'         },
    { number: 20,  name: 'طه',         nameEn: 'Ta-Ha'          },
    { number: 21,  name: 'الأنبياء',   nameEn: 'Al-Anbiya'      },
    { number: 22,  name: 'الحج',       nameEn: 'Al-Hajj'        },
    { number: 23,  name: 'المؤمنون',   nameEn: 'Al-Muminun'     },
    { number: 24,  name: 'النور',      nameEn: 'An-Nur'         },
    { number: 25,  name: 'الفرقان',    nameEn: 'Al-Furqan'      },
    { number: 26,  name: 'الشعراء',    nameEn: 'Ash-Shuara'     },
    { number: 27,  name: 'النمل',      nameEn: 'An-Naml'        },
    { number: 28,  name: 'القصص',      nameEn: 'Al-Qasas'       },
    { number: 29,  name: 'العنكبوت',   nameEn: 'Al-Ankabut'     },
    { number: 30,  name: 'الروم',      nameEn: 'Ar-Rum'         },
    { number: 31,  name: 'لقمان',      nameEn: 'Luqman'         },
    { number: 32,  name: 'السجدة',     nameEn: 'As-Sajda'       },
    { number: 33,  name: 'الأحزاب',    nameEn: 'Al-Ahzab'       },
    { number: 34,  name: 'سبأ',        nameEn: 'Saba'           },
    { number: 35,  name: 'فاطر',       nameEn: 'Fatir'          },
    { number: 36,  name: 'يس',         nameEn: 'Ya-Sin'         },
    { number: 37,  name: 'الصافات',    nameEn: 'As-Saffat'      },
    { number: 38,  name: 'ص',          nameEn: 'Sad'            },
    { number: 39,  name: 'الزمر',      nameEn: 'Az-Zumar'       },
    { number: 40,  name: 'غافر',       nameEn: 'Ghafir'         },
    { number: 41,  name: 'فصلت',       nameEn: 'Fussilat'       },
    { number: 42,  name: 'الشورى',     nameEn: 'Ash-Shura'      },
    { number: 43,  name: 'الزخرف',     nameEn: 'Az-Zukhruf'     },
    { number: 44,  name: 'الدخان',     nameEn: 'Ad-Dukhan'      },
    { number: 45,  name: 'الجاثية',    nameEn: 'Al-Jathiya'     },
    { number: 46,  name: 'الأحقاف',    nameEn: 'Al-Ahqaf'       },
    { number: 47,  name: 'محمد',       nameEn: 'Muhammad'       },
    { number: 48,  name: 'الفتح',      nameEn: 'Al-Fath'        },
    { number: 49,  name: 'الحجرات',    nameEn: 'Al-Hujurat'     },
    { number: 50,  name: 'ق',          nameEn: 'Qaf'            },
    { number: 51,  name: 'الذاريات',   nameEn: 'Adh-Dhariyat'   },
    { number: 52,  name: 'الطور',      nameEn: 'At-Tur'         },
    { number: 53,  name: 'النجم',      nameEn: 'An-Najm'        },
    { number: 54,  name: 'القمر',      nameEn: 'Al-Qamar'       },
    { number: 55,  name: 'الرحمن',     nameEn: 'Ar-Rahman'      },
    { number: 56,  name: 'الواقعة',    nameEn: 'Al-Waqia'       },
    { number: 57,  name: 'الحديد',     nameEn: 'Al-Hadid'       },
    { number: 58,  name: 'المجادلة',   nameEn: 'Al-Mujadila'    },
    { number: 59,  name: 'الحشر',      nameEn: 'Al-Hashr'       },
    { number: 60,  name: 'الممتحنة',   nameEn: 'Al-Mumtahina'   },
    { number: 61,  name: 'الصف',       nameEn: 'As-Saf'         },
    { number: 62,  name: 'الجمعة',     nameEn: 'Al-Jumuah'      },
    { number: 63,  name: 'المنافقون',  nameEn: 'Al-Munafiqun'   },
    { number: 64,  name: 'التغابن',    nameEn: 'At-Taghabun'    },
    { number: 65,  name: 'الطلاق',     nameEn: 'At-Talaq'       },
    { number: 66,  name: 'التحريم',    nameEn: 'At-Tahrim'      },
    { number: 67,  name: 'الملك',      nameEn: 'Al-Mulk'        },
    { number: 68,  name: 'القلم',      nameEn: 'Al-Qalam'       },
    { number: 69,  name: 'الحاقة',     nameEn: 'Al-Haqqah'      },
    { number: 70,  name: 'المعارج',    nameEn: 'Al-Maarij'      },
    { number: 71,  name: 'نوح',        nameEn: 'Nuh'            },
    { number: 72,  name: 'الجن',       nameEn: 'Al-Jinn'        },
    { number: 73,  name: 'المزمل',     nameEn: 'Al-Muzzammil'   },
    { number: 74,  name: 'المدثر',     nameEn: 'Al-Muddaththir' },
    { number: 75,  name: 'القيامة',    nameEn: 'Al-Qiyama'      },
    { number: 76,  name: 'الإنسان',    nameEn: 'Al-Insan'       },
    { number: 77,  name: 'المرسلات',   nameEn: 'Al-Mursalat'    },
    { number: 78,  name: 'النبأ',      nameEn: 'An-Naba'        },
    { number: 79,  name: 'النازعات',   nameEn: 'An-Naziat'      },
    { number: 80,  name: 'عبس',        nameEn: 'Abasa'          },
    { number: 81,  name: 'التكوير',    nameEn: 'At-Takwir'      },
    { number: 82,  name: 'الانفطار',   nameEn: 'Al-Infitar'     },
    { number: 83,  name: 'المطففين',   nameEn: 'Al-Mutaffifin'  },
    { number: 84,  name: 'الانشقاق',   nameEn: 'Al-Inshiqaq'    },
    { number: 85,  name: 'البروج',     nameEn: 'Al-Buruj'       },
    { number: 86,  name: 'الطارق',     nameEn: 'At-Tariq'       },
    { number: 87,  name: 'الأعلى',     nameEn: 'Al-Ala'         },
    { number: 88,  name: 'الغاشية',    nameEn: 'Al-Ghashiya'    },
    { number: 89,  name: 'الفجر',      nameEn: 'Al-Fajr'        },
    { number: 90,  name: 'البلد',      nameEn: 'Al-Balad'       },
    { number: 91,  name: 'الشمس',      nameEn: 'Ash-Shams'      },
    { number: 92,  name: 'الليل',      nameEn: 'Al-Layl'        },
    { number: 93,  name: 'الضحى',      nameEn: 'Ad-Duha'        },
    { number: 94,  name: 'الشرح',      nameEn: 'Ash-Sharh'      },
    { number: 95,  name: 'التين',      nameEn: 'At-Tin'         },
    { number: 96,  name: 'العلق',      nameEn: 'Al-Alaq'        },
    { number: 97,  name: 'القدر',      nameEn: 'Al-Qadr'        },
    { number: 98,  name: 'البينة',     nameEn: 'Al-Bayyina'     },
    { number: 99,  name: 'الزلزلة',    nameEn: 'Az-Zalzala'     },
    { number: 100, name: 'العاديات',   nameEn: 'Al-Adiyat'      },
    { number: 101, name: 'القارعة',    nameEn: 'Al-Qaria'       },
    { number: 102, name: 'التكاثر',    nameEn: 'At-Takathur'    },
    { number: 103, name: 'العصر',      nameEn: 'Al-Asr'         },
    { number: 104, name: 'الهمزة',     nameEn: 'Al-Humaza'      },
    { number: 105, name: 'الفيل',      nameEn: 'Al-Fil'         },
    { number: 106, name: 'قريش',       nameEn: 'Quraysh'        },
    { number: 107, name: 'الماعون',    nameEn: 'Al-Maun'        },
    { number: 108, name: 'الكوثر',     nameEn: 'Al-Kawthar'     },
    { number: 109, name: 'الكافرون',   nameEn: 'Al-Kafirun'     },
    { number: 110, name: 'النصر',      nameEn: 'An-Nasr'        },
    { number: 111, name: 'المسد',      nameEn: 'Al-Masad'       },
    { number: 112, name: 'الإخلاص',    nameEn: 'Al-Ikhlas'      },
    { number: 113, name: 'الفلق',      nameEn: 'Al-Falaq'       },
    { number: 114, name: 'الناس',      nameEn: 'An-Nas'         },
];

module.exports = { TOKEN, LOGO, PAGE_SIZE, RECITERS, SURAHS, SURAH_AYAH_COUNTS };